[package]
name = "alephc"
version = "1.0.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3 

[dependencies]
aleph-syntax-tree = { path = "../aleph-syntax-tree" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
argparse = "0.2.2"
aleparser = { path = "../filter/parser/aleparser" }
python_parser = { path = "src/filter/parser/python/pythonparser" }

[features]
"ale_parse" = []
"json_parse" = []
"ale_gen" = []
"java_gen" = []
"json_gen" = []
"ocaml_gen" = []
"python_gen" = []
"rust_gen" = []
"python_parse" = []
"default" = ["ale_gen","json_gen" ,"ale_parse","json_parse" ]

[workspace]
members = [
    "src/filter/parser/python/pythonparser"
]
