[package]
name = "aleph-ws"
version = "1.0.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3 

[dependencies]
actix-web = "4"
env_logger = "0.9"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
json = "0.12"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking"] } # remove feature blocking and add tokio for async requests
rust-sitter = "0.1.2"

[build-dependencies]
rust-sitter-tool = "0.1.2"

[features]
"ale_parse" = []
"json_parse" = []
"ale_gen" = []
"bash_gen" = []
"java_gen" = []
"json_gen" = []
"ocaml_gen" = []
"python_gen" = []
"rust_gen" = []
"default" = ["ale_gen","json_gen" ,"ale_parse","json_parse" ]
