[package]
name = "aleph-ws"
version = "1.0.0"
edition = "2021"
default-run = "alephc"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3 

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-sitter = "0.1.2"
awc = { version = "3.0.0-beta.11", features = [ "openssl" ] }
argparse = "0.2.2"

[build-dependencies]
rust-sitter-tool = "0.1.2"

[features]
"ale_parse" = []
"json_parse" = []
"ale_gen" = []
"bash_gen" = []
"java_gen" = []
"json_gen" = []
"ocaml_gen" = []
"python_gen" = []
"rust_gen" = []
"default" = ["ale_gen","json_gen" ,"ale_parse","json_parse" ]

[[bin]]
name="aleph-cli"
path="src/client/mod.rs"

[[bin]]
name="alephc"
path="src/alephc.rs"

