[package]
name = "aleparser"
version = "0.1.0"
edition = "2021"

[dependencies]
aleph-syntax-tree = { path = "../../../../../../aleph-syntax-tree" }
rust-sitter = "0.1.2"

[build-dependencies]
rust-sitter-tool = "0.1.2"
